# Generated by Django 5.2.1 on 2025-05-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Available Quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='cart_summary',
            field=models.CharField(default='Default cart summary', help_text='Short description that will appear in the cart', max_length=255, verbose_name='Cart Summary'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_domestic',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Domestic Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_international',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='International Price'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
