# Generated by Django 5.2.1 on 2025-05-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, max_length=255, verbose_name='Colors'),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Length (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.CharField(blank=True, max_length=255, verbose_name='Materials'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Width (cm)'),
        ),
    ]
